name: srhcraftshop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter # This is the correct way to specify Flutter SDK
  provider: ^6.0.2 # This is where you specify the provider package version
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.8
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/basketpic.webp
    - assets/loading.jpg
    - assets/srhmodularlogo.png
    - assets/logo3.png



  
