name: srhcraftshop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/basketpic.webp
    - assets/loading.jpg
    - assets/srhmodularlogo.png
    - assets/logo3.png




  
